name: Gradle CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Initialize JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ZtereoMUSIC
          path: build/libs/ZtereoMUSIC-0.0.2-all.jar
      
      - name: Tell the server to update the bot
        uses: wei/curl@v1
        with:
          args: -X POST http://81.240.64.77:5000/actionsBuilt
